---
- hosts: manual
  tasks:


    - name: Mise à jour
      apt:
        upgrade: yes
        update_cache: yes

#########################################
#                                       #
### Partie I : Logiciel en complément ###
#                                       #
#########################################

    - name: Installer java 8
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Définition de java
      shell: echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> environment

    - name: Installation de unzip
      apt:
        name: unzip
        state: present
    
    - name: Téléchargement et décompression de SquirrelSQL
      unarchive: 
        src: https://github.com/PurpleNyx/SquirrelSQL/archive/master.zip 
        dest: /tmp
        remote_src: yes

    - name: Installer firefox
      apt:
        force: yes
        name: firefox
        state: present

    - name: Installer chromium
      apt:
        force: yes
        name: chromium-browser
        state: present

    - name: Téléchargement et décompression de SoapUI-5.4
      unarchive: 
        src: https://s3.amazonaws.com/downloads.eviware/soapuios/5.4.0/SoapUI-5.4.0-linux-bin.tar.gz
        dest: /opt
        remote_src: yes

    - name: Téléchargement et décompression de ZAProxy
      unarchive: 
        src: https://github.com/zaproxy/zaproxy/tarball/master
        dest: /tmp
        remote_src: yes
