---
- hosts: manual
  tasks:

# EN BREF : CHROME C'EST DE LA MERDE, VIVE L'OPEN SOURCE !
    #- name: get_url chrome
     # get_url: 
      #  url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
       # dest: /tmp
        #mode: 0644

    #- name: Ajout dépot chrome
     # apt_key:
      # url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
       #state: present

    - name: Mise à jour
      apt:
        upgrade: yes
        update_cache: yes

# ANNULATION DE L'INSTALLATION DE CHROME SUITE A TA MERE D'ERREUR DE TOI LE MODULE ANSIBLE DPKG
    #- dpkg_selections:
     #  name: google-chrome-stable_current_amd64.deb
      # selection: install

    - name: Installer java 8
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Définition de java
      shell: echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> environment

    - name: Installation de unzip
      apt:
        name: unzip
        state: present
    
    - name: Téléchargement et décompression de SquirrelSQL
      unarchive: 
        src: https://github.com/PurpleNyx/SquirrelSQL/archive/master.zip 
        dest: /tmp
        remote_src: yes

    - name: Installer firefox
      apt:
        force: yes
        name: firefox
        state: present

    - name: Installer chromium
      apt:
        force: yes
        name: chromium-browser
        state: present

    - name: Téléchargement et décompression de SoapUI-5.4
      unarchive: 
        src: https://s3.amazonaws.com/downloads.eviware/soapuios/5.4.0/SoapUI-5.4.0-linux-bin.tar.gz
        dest: /opt
        remote_src: yes

    - name: Téléchargement et décompression de ZAProxy
      unarchive: 
        src: https://github.com/zaproxy/zaproxy/tarball/master
        dest: /tmp
        remote_src: yes
