---
- hosts: manual
  tasks:


    - name: Mise à jour
      apt:
        upgrade: yes
        update_cache: yes

#########################################
#                                       #
### Partie I : Logiciel en complément ###
#                                       #
#########################################

    - name: Installer java 8
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Définition de java
      shell: echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> environment

    - name: Installation de unzip
      apt:
        name: unzip
        state: present
    
    - name: Téléchargement et décompression de SquirrelSQL
      unarchive: 
        src: https://github.com/PurpleNyx/SquirrelSQL/archive/master.zip 
        dest: /home
        remote_src: yes
        
    - name: Installation de SquirrelSQL 
      shell: cp /home/install /home/SquirrelSQL-master/ && cd /home/SquirrelSQL-master/ && java -jar squirrel-sql-4.0.0-standard.jar install 
      
    - name: Déplacement des drivers postgresql et mysql dans le dossier d'installation de SquirrelSQL 
      shell: cp /home/SquirrelSQL-master/driver_ubuntu/mysql-connector-java-8.0.17.jar /home/formation/squirrel-sql-4.0.0/plugins/mysql && cp /home/SquirrelSQL-master/driver_ubuntu/postgresql.jar /home/formation/squirrel-sql-4.0.0/plugins/postgres/lib
    
    - name: Lancement de l'interface Squirrel Client 
      shell: cd /home/formation/squirrel-sql-4.0.0 && java -jar squirrel-squirrel-sql.jar

    - name: Installer firefox
      apt:
        force: yes
        name: firefox
        state: present

    - name: Installer chromium
      apt:
        force: yes
        name: chromium-browser
        state: present

    - name: Téléchargement et décompression de SoapUI-5.4
      unarchive: 
        src: https://s3.amazonaws.com/downloads.eviware/soapuios/5.4.0/SoapUI-5.4.0-linux-bin.tar.gz
        dest: /opt
        remote_src: yes

    - name: Téléchargement et décompression de ZAProxy
      unarchive: 
        src: https://github.com/zaproxy/zaproxy/tarball/master
        dest: /
        remote_src: yes
