---
- hosts: logimysql
  tasks:

    # Mise à jour de base pour actualiser le conteneur
    - name: Mise à jour
      apt:
        force: yes
        upgrade: yes
        update_cache: yes


#########################################
#                                       #
### Partie I : Installation mysql BDD ###
#                                       #
#########################################


    # Installation de mysql
    - name: Installer mysql
      apt:
        force: yes
        name: mysql-server
        state: present

    # Ouverture de tous les ports d'écoute (inutile car déploiment du logiciel en local mais permet vérif à distance)
    # FAILLE FAILLE FAILLE FAILLE FAILLE FAILLE FAILLE FAILLE FAILLE FAILLE FAILLE FAILLE FAILLE FAILLE FAILLE
    # SECURITE SECURITE SECURITE SECURITE SECURITE SECURITE SECURITE SECURITE SECURITE SECURITE SECURITE SECURITE
    # FAILLE FAILLE FAILLE FAILLE FAILLE FAILLE FAILLE FAILLE FAILLE FAILLE FAILLE FAILLE FAILLE FAILLE FAILLE
    # SECURITE SECURITE SECURITE SECURITE SECURITE SECURITE SECURITE SECURITE SECURITE SECURITE SECURITE SECURITE
    - name: Changement config mysql 
      shell: sed -i 's/127.0.0.1/0.0.0.0/' /etc/mysql/mysql.conf.d/mysqld.cnf
      notify: faille
      
    # Démarrer le service mysql
    - name: Démarrer mysql via shell
      shell: service mysql start
      notify: mysql start

    # Installation de PyMySQL pour les manipulations de bases à l'aide d'Ansible
    - name: Installer PyMySQL
      apt:
        name: python-pymysql
        state: present

    # Création d'un utilisateur autre que root pour utilisation ultérieure
    - name: Créer un utilisateur mysql
      mysql_user:
        login_user: root
        login_password: ''
        name: logicaldoc
        password: logicaldoc
        host: '%'
        priv: '*.*:ALL,GRANT'
        state: present
      notify: user admin

    # Création de la BDD
    - name: Créer une base logicaldoc et la remplir
      mysql_db:
       login_user: root
       name: logicaldoc
       state: import
       target: /dumpmysql.sql


#########################################
#                                       #
## Partie II : Installation LogicalDoc ##
#                                       #
#########################################


    # Installation de java 8 pour Apache-Tomcat & LogicalDoc
    - name: Installer java 8
      apt:
        name: openjdk-8-jdk
        state: present

    # Récupération des sources d'Apache-Tomcat-8
    - name: Téléchargement et décompression de Apache-Tomcat-8.5.46
      unarchive: 
        src: http://apache.mirrors.benatherton.com/tomcat/tomcat-8/v8.5.46/bin/apache-tomcat-8.5.46.tar.gz
        dest: /home
        remote_src: yes

    # Téléchargement de LogicalDoc (module Ansible get_url non fonctionnel pour une exécution ultérieure dans Tomcat)
    - name: Téléchargement de LogicalDoc
      shell: cd /home/apache-tomcat-8.5.46/webapps && wget https://www.dropbox.com/s/cf999m4djxm6m7z/logicaldoc.war

    # Extraction du .war via jar
    - name: Extraction de logicaldoc.war
      shell: cd /home/apache-tomcat-8.5.46/webapps && mkdir logicaldoc && cd logicaldoc && jar -xvf /home/apache-tomcat-8.5.46/webapps/logicaldoc.war

    
#########################################
#                                       #
## Partie III : Paramétrage LogicalDoc ##
#                                       #
#########################################


    # lineinfile est un module Ansible de "find and replace" plus efficace que sed en shell

    - name: Modification context.properties jdbc.dbms
      lineinfile:
        path: /home/apache-tomcat-8.5.46/webapps/logicaldoc/WEB-INF/classes/context.properties
        regexp: jdbc.dbms=hsqldb
        line: jdbc.dbms=mysql

    - name: Modification context.properties jdbc.driver
      lineinfile:
        path: /home/apache-tomcat-8.5.46/webapps/logicaldoc/WEB-INF/classes/context.properties
        regexp: jdbc.driver=org.hsqldb.jdbc.JDBCDriver
        line: jdbc.driver=com.mysql.jdbc.Driver

    - name: Modification context.properties jdbc.url
      lineinfile:
        path: /home/apache-tomcat-8.5.46/webapps/logicaldoc/WEB-INF/classes/context.properties
        regexp: jdbc.url=jdbc:hsqldb:mem:logicaldoc
        line: jdbc.url=jdbc:mysql://localhost:3306/logicaldoc

    - name: Modification context.properties jdbc.password
      lineinfile:
        path: /home/apache-tomcat-8.5.46/webapps/logicaldoc/WEB-INF/classes/context.properties
        regexp: jdbc.password=
        line: jdbc.password=logicaldoc

    - name: Modification context.properties jdbc.username
      lineinfile:
        path: /home/apache-tomcat-8.5.46/webapps/logicaldoc/WEB-INF/classes/context.properties
        regexp: jdbc.username=sa 
        line: jdbc.username=logicaldoc


#########################################
#                                       #
#### Partie IV : Lancement du Tomcat ####
#                                       #
#########################################


    # Création d'un fichier de lancement de Apache-Tomcat
    # Nécessaire pour un lancement automatique sans dépassement de mémoire
    - name: Création fichier de lancement sh
      shell: echo "#!/bin/sh" > startall.sh

    - name: Ajout de l'option de séparation des processus
      shell: echo "set -m" >> startall.sh

    - name: Ajout du lancement de Apache-Tomcat-8
      shell: echo "sh /home/apache-tomcat-8.5.46/bin/startup.sh" >> startall.sh

    - name: Lancement de Apache-Tomcat-8
      shell: sh startall.sh
      register: TomcatLaunch
    - debug: var=TomcatLaunch


#########################################
#                                       #
### Partie V : Logiciel en complément ###
#                                       #
#########################################


    - name: Téléchargement et décompression de SoapUI-5.4
      unarchive: 
        src: https://s3.amazonaws.com/downloads.eviware/soapuios/5.4.0/SoapUI-5.4.0-linux-bin.tar.gz
        dest: /opt
        remote_src: yes


#########################################
#                                       #
###### Partie VI : Appels handlers ######
#                                       #
#########################################


  handlers:
   - name: user admin
     debug:
       msg: L'utilisateur a été créé

   - name: mysql start
     debug:
       msg: Démarrage du service de base de données

   - name: faille
     debug:
       msg: FAILLE DE SECURITE PRESENTE SUR LA BASE DE DONNEES ! Si vous lisez ce message c'est que vous avez oublié de retirer l'ouverture de tous les ports de la BDD.